// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image_section: dynamic(() => import("./ImageSection")),
  slice2: dynamic(() => import("./Slice2")),
};
